### PR TITLE
Up for review and approval

### PR DESCRIPTION
**Pull request by emmanjames12**
This form must be converted in PDF after being processed.

### CODE REVIEW

**Review by NaitoXyan — CHANGES_REQUESTED** [review]
I merge request sa develop branch

**Comment by NaitoXyan** [comment]
merge request sa develop branch

**Comment by emmanjames12** [comment]
Okayyy chal, plan sab nko to do that👌tnx

EMMANUELLE JAMES P. DUALLO

Bachelor of Science in Information Technology | 3R4_Track 1

College of Information Technology and Computing

UNIVERSITY OF SCIENCE AND TECHNOLOGY OF SOUTHERN PHILIPPINES – CDO

Email: ***@***.***

Facebook: www.facebook.com/dualloemmanuellejames/

Contact Number: +63 906 951 9573



DISCLAIMER: This e-mail communication and any attachments may contain
confidential and privileged information for the use of the designated
recipients named above. If you are not the intended recipient, you are
hereby notified that you have received this communication in error and that
any review, disclosure, dissemination, distribution or copying of it or its
contents is strictly prohibited. If you have received this communication in
error, please notify the sender by return e-mail and delete and/or destroy
all copies of this communication and any attachments.


Disclaimer:

The information in this electronic message is privileged and confidential,
intended only for use of the individual or entity named as addressee and
recipient. If you are not the addressee indicated in this message (or
responsible for delivery of the message to such person), you may not copy,
use, disseminate or deliver this message. In such case, you should
immediately delete this e-mail and notify the sender by reply e-mail.
Please advise immediately if you or your employer do not consent to
Internet e-mail for messages of this kind. Opinions, conclusions and other
information expressed in this message are not given, nor endorsed by and
are not the responsibility of USTP unless otherwise indicated by an
authorized representative of USTP independent of this message.

**Comment by emmanjames12** [comment]
Okayyyy lods

EMMANUELLE JAMES P. DUALLO

Bachelor of Science in Information Technology | 3R4_Track 1

College of Information Technology and Computing

UNIVERSITY OF SCIENCE AND TECHNOLOGY OF SOUTHERN PHILIPPINES – CDO

Email: ***@***.***

Facebook: www.facebook.com/dualloemmanuellejames/

Contact Number: +63 906 951 9573



DISCLAIMER: This e-mail communication and any attachments may contain
confidential and privileged information for the use of the designated
recipients named above. If you are not the intended recipient, you are
hereby notified that you have received this communication in error and that
any review, disclosure, dissemination, distribution or copying of it or its
contents is strictly prohibited. If you have received this communication in
error, please notify the sender by return e-mail and delete and/or destroy
all copies of this communication and any attachments.


Disclaimer:

The information in this electronic message is privileged and confidential,
intended only for use of the individual or entity named as addressee and
recipient. If you are not the addressee indicated in this message (or
responsible for delivery of the message to such person), you may not copy,
use, disseminate or deliver this message. In such case, you should
immediately delete this e-mail and notify the sender by reply e-mail.
Please advise immediately if you or your employer do not consent to
Internet e-mail for messages of this kind. Opinions, conclusions and other
information expressed in this message are not given, nor endorsed by and
are not the responsibility of USTP unless otherwise indicated by an
authorized representative of USTP independent of this message.

**Comment by emmanjames12** [comment]
[ProposalFormFirstPage_Deliverables] IN CASE WALA NA PUSH ANG DELIVERABLES

import React, { useState } from 'react';

import ProjLeadSideBar from './ProjLeadSideBar';
import Topbar from './Topbar'; 

const ProposalFormFirstPage_Deliverables = () => {
  const [showTextField, setShowTextField] = useState(false);

  const handleCheckboxChange = (event) => {
    setShowTextField(event.target.checked);
  };

  return (
    <div className="bg-gray-200 min-h-screen flex">
      {/* Sidebar */}
      <div className="w-1/5 fixed h-full">
        <ProjLeadSideBar />
      </div>
      
      {/* Main Content */}
      <div className="flex-1 ml-[20%]">
        <Topbar />
        
        <div className="p-8">
          <h2 className="text-2xl font-semibold mb-4 mt-10">Proponents Deliverables</h2>
          <div className="bg-white p-6 rounded-lg shadow-md">
            
            {/* Form Fields */}
            <div className="grid grid-cols-2 gap-4 mb-4">
              <div>
                <label className="block text-gray-700">Project Title</label>
                <input type="text" placeholder="Title" className="w-full mt-1 p-2 border border-gray-300 rounded" />
              </div>
              
              <div>
                <label className="block text-gray-700">Date of Implementation</label>
                <input type="date" className="w-full mt-1 p-2 border border-gray-300 rounded" />
              </div>
              
              <div>
                <label className="block text-gray-700">Prepared by:</label>
                <input type="text" placeholder="Main Proponent/Project Leader" className="w-full mt-1 p-2 border border-gray-300 rounded" />
              </div>
              
              <div>
                <label className="block text-gray-700">Noted by:</label>
                <input type="text" value="DR. MARIA TERESA M. FAJARDO" readOnly className="w-full mt-1 p-2 border border-gray-300 rounded bg-gray-100" />
              </div>
            </div>

            {/* Checklist */}
            <h3 className="text-lg font-semibold mb-1 mt-10">Sigfred Tong</h3>
            <p className="text-sm italic font-normal text-gray-600 mb-5">(Main Proponent/Project Leader)</p>

            <div className="grid grid-cols-2 gap-2 text-gray-700 mr-5">
              <label className="flex items-center">
                <input type="checkbox" className="mr-2" /> Letter request from requesting party
              </label>
              <label className="flex items-center">
                <input type="checkbox" className="mr-2" /> Daily Attendance Sheet
              </label>
              <label className="flex items-center">
                <input type="checkbox" className="mr-2" /> Letter response to requesting party (within 3 days)
              </label>
              <label className="flex items-center">
                <input type="checkbox" className="mr-2" /> Evaluation Sheets
              </label>
              <label className="flex items-center">
                <input type="checkbox" className="mr-2" /> Approved Project Proposal or Letter to Conduct Activity
              </label>
              <label className="flex items-center">
                <input type="checkbox" className="mr-2" /> Summary of Evaluation (in Excel form)
              </label>
              <label className="flex items-center">
                <input type="checkbox" className="mr-2" /> Loading of Trainers
              </label>
              <label className="flex items-center">
                <input type="checkbox" className="mr-2" /> Trainers CV
              </label>
              <label className="flex items-center">
                <input type="checkbox" className="mr-2" /> MOA/MOU
              </label>
              <label className="flex items-center">
                <input type="checkbox" className="mr-2" /> Trainers DTR
              </label>
              <label className="flex items-center">
                <input type="checkbox" className="mr-2" /> Progress/Accomplishment/Terminal Report (include pictures with captions)
              </label>
              <label className="flex items-center">
                <input type="checkbox" className="mr-2" /> Modules/Lecture Notes
              </label>
              <label className="flex items-center">
                <input type="checkbox" className="mr-2" /> List of Participants
              </label>
              <label className="flex items-center">
                <input 
                  type="checkbox" 
                  className="mr-2" 
                  onChange={handleCheckboxChange} 
                /> 
                Others
              </label>
              {showTextField && (
                <input 
                  type="text" 
                  className="mt-2 p-2 border border-gray-300 rounded w-full" 
                  placeholder="Please specify..." 
                />
              )}
            </div>

            {/* Submit Button */}
            <div className="text-center mt-6">
              <button className="bg-yellow-500 hover:bg-yellow-600 text-white py-2 px-4 rounded">
                Submit Checklist
              </button>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default ProposalFormFirstPage_Deliverables;

**Pull request closed without merging**
